sudo: false
language: python

stages:
#  - lint
#  - test  
  # python packages always built for master, but only deployed for a
  # ^v tag
  #
  # conda dev package always built and uploaded for master; regular
  # conda package only uploaded for a ^v tag.
  #
  - name: pypi_package
    if: (branch = master AND type != pull_request) OR (tag =~ ^v)
  - name: conda_dev_package
    if: (branch = master AND type != pull_request) OR (tag =~ ^v)
  - name: conda_package
    if: tag =~ ^v

jobs:
  include:

  - <<: *default
    stage: pypi_package
    install: true
    script: true
    deploy:
      provider: pypi
      distributions: "sdist bdist_wheel"
      on:
        tags: true
      user: ceball
      password:
        secure: $PYPIPWD

  - &conda_default
    stage: conda_dev_package
    install:
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - conda config --set always_yes yes --set changeps1 no
      - conda update conda
      - conda install anaconda-client conda-build
      - conda build conda.recipe/      
    script:
      # TODO: need to upload only if package doesn't exist (as e.g. there are cron builds)
      - anaconda --token $CONDA_UPLOAD_TOKEN upload --user pyviz --label dev `conda build --output conda.recipe`

  - <<: *conda_default
    stage: conda_package
    script:
      - anaconda --token $CONDA_UPLOAD_TOKEN upload --user pyviz `conda build --output conda.recipe`
