sudo: false
language: generic

stages:
  - flakes
  - test
  - name: pip_dev_package
    if: (branch = master AND type != pull_request) AND (NOT tag =~ ^v)
  - name: pip_package
    if: tag =~ ^v    
#  - name: conda_check_py27
#    if: (branch = master AND type != pull_request) OR (tag =~ ^v)
#  - name: conda_dev_package
#    if: (branch = master AND type != pull_request) AND (NOT tag =~ ^v)
#  - name: conda_package
#    if: tag =~ ^v

jobs:
  include:

  ########## TEST DEVELOPER INSTALL ##########  

  ## pip
  
  - &pip_default
    stage: test
    env: PYENV_VERSION=3.6
    # (pyct requires itself to test itself)
    before_install: pip install -e .
    install: doit develop_install
    script: doit test_unit

  - <<: *pip_default
    stage: flakes
    script: doit test_flakes

  ## conda

#  - &conda_default
#    stage: test
#    env: PYCT_ECOSYSTEM=conda PYENV_VERSION=3.6
#    before_install:
#      ## install miniconda (using git pyct)
#      - pip install -e . && doit miniconda_install && pip uninstall -y doit pyct && rm -f .doit.db
#      - export PATH="$HOME/miniconda/bin:$PATH"
#      ## build conda package (using git pyct)
#      - pip install -e . && doit ecosystem_setup && doit package_build -c pyviz/label/dev -c conda-forge && pip uninstall -y doit pyct && rm -f .doit.db
#      ## install conda package to use for rest of tests
#      - conda install -y --use-local -c conda-forge pyct
#    install: doit develop_install -c conda-forge
#    script: doit test_unit


  ########## BUILD/TEST/UPLOAD END-USER PACKAGES ##########

  ##### pip

  - &pip_pkg_default
    stage: pip_dev_package
    env: PYENV_VERSION=3.6 PYPI="https://test.pypi.org/legacy/"
    before_install:
      - pip install -e .
      - doit ecosystem_setup      
    install: doit package_build
    script: doit package_upload -u ceball -p $PYPIPWD -r ${PYPI}

  - <<: *pip_pkg_default
    env: PYENV_VERSION=2.7 PYPI="https://test.pypi.org/legacy/"
    # sdist same as for 3.6
    install: doit package_build --formats="bdist_wheel"

  - <<: *pip_pkg_default
    stage: pip_package
    env: PYENV_VERSION=3.6 PYPI="https://upload.pypi.org/legacy/"

  - <<: *pip_pkg_default
    stage: pip_package
    env: PYENV_VERSION=2.7 PYPI="https://upload.pypi.org/legacy/"
    # sdist same as for 3.6
    install: doit package_build --formats="bdist_wheel"


  ##### conda

#  - <<: *conda_default
#    stage: conda_dev_package
#    install: doit package_build -c pyviz/label/dev -c conda-forge
#    script: doit package_upload --token=$CONDA_UPLOAD_TOKEN --label=dev
#
#  # pyct is noarch:python but doit isn't, so check ok on py27
#  - <<: *conda_default
#    stage: conda_check_py27
#    install: doit package_build -c pyviz/label/dev -c conda-forge --python 2.7
#    script: true
#
#  - <<: *conda_default
#    stage: conda_package
#    install: doit package_build -c pyviz/label/dev -c conda-forge
#    script: doit package_upload --token=$CONDA_UPLOAD_TOKEN --label=main --label=dev


