sudo: false
language: python
python:
  - "3.6"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda install anaconda-client conda-build
script:
  - conda build -c conda-forge conda.recipe/
  # TODO: need to upload only if package doesn't exist (as e.g. there are cron builds)
  - anaconda --token $CONDA_UPLOAD_TOKEN upload --user pyviz --label dev `conda build --output conda.recipe`

deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    on:
      tags: true
    user: ceball
    password: $PYPIPWD
