sudo: false
language: generic

stages:
  - flakes
  - test
  - name: pip_package
    if: (branch = master AND type != pull_request) OR (tag =~ ^v)
  - name: conda_dev_package
    if: (branch = master AND type != pull_request) AND (NOT tag =~ ^v)
  - name: conda_package
    if: tag =~ ^v

jobs:
  include:

  ########## TEST DEVELOPER INSTALL ##########  

  ## pip
  
  - &pip_default
    stage: test
    env: PYENV_VERSION=3.6
    install: doit develop_install
    script: doit test_unit

  - <<: *pip_default
    stage: flakes
    script: doit test_flakes

  ## conda

  - &conda_default
    stage: test
    env: PYCT_ECOSYSTEM=conda PYENV_VERSION=3.6
    before_install:
      ## install miniconda (using git pyct)
      - pip install -e . && doit miniconda_install && pip uninstall -y doit pyct && rm -f .doit.db
      - export PATH="$HOME/miniconda/bin:$PATH"
      ## build conda package (using git pyct)
      - pip install -e . && doit ci_configure && doit package_build -c conda-forge && pip uninstall -y doit pyct && rm -f .doit.db
      ## install conda package to use for rest of tests
      - conda install -y --use-local -c conda-forge pyct
    install: doit develop_install -c conda-forge
    script: doit test_unit


  ########## BUILD/TEST/UPLOAD END-USER PACKAGES ##########

  ##### pip

  - &pip_pkg_default
    stage: pip_package
    env: PYENV_VERSION=3.6
    before_install: pip install tox py2venv tox-pip-extensions
    install: true
    script: doit package_build
    ###
    # TODO: change to a doit command so not dependent on travis
    deploy:
      provider: pypi
      distributions: "sdist bdist_wheel"
      on:
        tags: true
      user: ceball
      password:
        secure: $PYPIPWD
    ###    

  - <<: *default
    env: PYENV_VERSION=2.7
    install: true
    ###
    # TODO: change to a doit command so not dependent on travis
    # (duplicated from above just to avoid sdist second time...)
    deploy:
      provider: pypi
      distributions: "bdist_wheel"
      on:
        tags: true
      user: ceball
      password:
        secure: $PYPIPWD
    ###    


  ##### conda

  # TODO: python2

  - <<: *conda_default
    stage: conda_dev_package
    install: doit package_build -c conda-forge
    script: doit package_upload --token=$CONDA_UPLOAD_TOKEN --label=dev

  - <<: *conda_default
    stage: conda_package
    install: doit package_build -c conda-forge
    script: doit package_upload --token=$CONDA_UPLOAD_TOKEN --label=main --label=dev
