sudo: false
language: python

stages:
  - lint
  - test
  - conda_test
  - name: pypi_package
    if: (branch = master AND type != pull_request) OR (tag =~ ^v)
  - name: conda_dev_package
    if: (branch = master AND type != pull_request) AND (NOT tag =~ ^v)
  - name: conda_package
    if: tag =~ ^v

jobs:
  include:

  - &default
    stage: test
    python: 3.6
    env: TOX_ENV=py36
    install: pip install tox
    script: tox -e $TOX_ENV

  - <<: *default
    stage: lint
    env: TOX_ENV=flakes

  - <<: *default
    stage: pypi_package
    python: 2.7
    install: true
    script: true
    deploy:
      provider: pypi
      distributions: "bdist_wheel"
      on:
        tags: true
      user: ceball
      password:
        secure: $PYPIPWD

  - <<: *default
    stage: pypi_package
    install: true
    script: true
    deploy:
      provider: pypi
      distributions: "sdist bdist_wheel"
      on:
        tags: true
      user: ceball
      password:
        secure: $PYPIPWD

  - &conda_default
    # like a conda-using developer
    stage: conda_test
    python: 3.6
    before_install:
      - pip install -e . && doit ecosystem=conda miniconda_install && pip uninstall -y doit pyct && rm -f .doit.db
      - export PATH="$HOME/miniconda/bin:$PATH"
      - pip install -e . && doit ecosystem=conda package_build -c conda-forge && pip install -y doit pyct && rm -f .doit.db
      ##
      - conda install --use-local -c conda-forge pyct
      - doit ci_configure
    install: doit develop_install --channel=conda-forge
    script: true # it's true there are no tests yet

  - <<: *conda_default
    stage: conda_dev_package
    python: 3.6
    install: doit package_build --channel conda-forge
    script: doit package_upload --token=$CONDA_UPLOAD_TOKEN --label=dev

  - <<: *conda_default
    stage: conda_package
    install: doit package_build --channel conda-forge
    script: doit package_upload --token=$CONDA_UPLOAD_TOKEN --label=main --label=dev
