sudo: false
language: generic

# quick hack to determine what tag is (improvements welcomed)
#     release: ^v(\d+|\.)*[^a-z]\d*$
# dev release: ^v(\d+|\.)*[a-z]\d*$

env:
  global:
    # will be overridden later to upload only wheel for py27 (sdist from py36)
    - PIP_FORMATS=""

stages:
  - test
  - name: pip_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$  
  - name: pip_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
#  - name: conda_check_py27
#    if: tag =~ ^v(\d+|\.)*[a-z]\d*$ OR (branch = master AND type != pull_request)
#  - name: conda_dev_package
#    if: tag =~ ^v(\d+|\.)*[a-z]\d*$ OR (branch = master AND type != pull_request)
#  - name: conda_package
#    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$

jobs:
  include:

  ########## TEST DEVELOPER INSTALL ##########  

  ## pip
  
  - &pip_default
    stage: test
    env: PYENV_VERSION=3.6
    # (pyct requires itself to test itself)
    before_install: pip install -e .
    install: doit develop_install
    script:
      - doit test_all
      - doit --dir=examples/one test_all

  ## conda

#  - &conda_default
#    stage: test
#    env: PYCT_ECOSYSTEM=conda PYENV_VERSION=3.6
#    before_install:
#      ## install miniconda (using git pyct)
#      - pip install -e . && doit miniconda_install && pip uninstall -y doit pyct && rm -f .doit.db
#      - export PATH="$HOME/miniconda/bin:$PATH"
#      ## build conda package (using git pyct)
#      - pip install -e . && doit ecosystem_setup && doit package_build -c pyviz/label/dev -c conda-forge && pip uninstall -y doit pyct && rm -f .doit.db
#      ## install conda package to use for rest of tests
#      - conda install -y --use-local -c conda-forge pyct
#    install: doit develop_install -c conda-forge
#    script:
#      - doit test_all
#      - doit --dir=examples/one test_all


  ########## BUILD/TEST/UPLOAD END-USER PACKAGES ##########

  ##### pip

  # (upload 2.7 packages first so that pypi displays 3's metadata)

  - &pip_pkg_default
    stage: pip_dev_package
    env: PYENV_VERSION=2.7 PYPI="https://test.pypi.org/legacy/" PIP_FORMATS="--formats=\"bdist_wheel\""
    before_install:
      - pip install -e .
      - doit ecosystem_setup
    install: doit package_build --test-python=py${PYENV_VERSION//./} --test-group=all $PIP_FORMATS
    script: doit package_upload -u ceball -p $PYPIPWD -r ${PYPI}

  - <<: *pip_pkg_default
    env: PYENV_VERSION=3.6 PYPI="https://test.pypi.org/legacy/"

  - <<: *pip_pkg_default
    stage: pip_package
    env: PYENV_VERSION=2.7 PYPI="https://upload.pypi.org/legacy/" PIP_FORMATS="--formats=\"bdist_wheel\""

  - <<: *pip_pkg_default
    stage: pip_package
    env: PYENV_VERSION=3.6 PYPI="https://upload.pypi.org/legacy/"


  ##### conda

#  - <<: *conda_default
#    stage: conda_dev_package
#    install: doit package_build -c pyviz/label/dev -c conda-forge --test-python=py${PYENV_VERSION//./} --test-group=all
#    script: doit package_upload --token=$CONDA_UPLOAD_TOKEN --label=dev
#
#  # pyct is noarch:python but doit isn't, so also check ok on py27
#  - <<: *conda_default
#    stage: conda_check_py27
#    install: doit package_build -c pyviz/label/dev -c conda-forge --test-python=py27 --test-group=all
#    script: true
#
#  - <<: *conda_default
#    stage: conda_package
#    install: doit package_build -c pyviz/label/dev -c conda-forge --test-python=py${PYENV_VERSION//./} --test-group=all
#    script: doit package_upload --token=$CONDA_UPLOAD_TOKEN --label=main --label=dev
#

