sudo: false
language: python

stages:
  - lint
#  - test  
  # python packages always built for master, but only deployed for a
  # ^v tag
  #
  # conda dev package always built and uploaded for master; regular
  # conda package only uploaded for a ^v tag.
  # TODO: decide what to do on dev channel for releases; a 'post0'?
  #
  - name: pypi_package
    if: (branch = master AND type != pull_request) OR (tag =~ ^v)
  - name: conda_dev_package
    if: (branch = master AND type != pull_request) OR (tag =~ ^v)
  - name: conda_package
    if: tag =~ ^v

jobs:
  include:

  - &default
    stage: test
    python: 3.6
    env: TOX_ENV=py36
    install:
      - pip install tox
    script:
      - tox -e $TOX_ENV

  - <<: *default
    stage: pypi_package
    install: true
    script: true
    deploy:
      provider: pypi
      distributions: "sdist bdist_wheel"
      on:
        tags: true
      user: ceball
      password:
        secure: $PYPIPWD

  - &conda_default
    stage: conda_dev_package
    before_install:
      #######################
      ## install miniconda ##
      - easy_install --user doit==0.29.0 pyct
      - ~/.local/bin/doit install_miniconda
      - rm -f .doit.db
      - export PATH="$HOME/miniconda/bin:$PATH"
      #######################
      - conda install -c pyviz/label/dev pyct
      - doit ci_configure_conda
    install:
      - doit build_conda_package
    script:
      - doit --token=$CONDA_UPLOAD_TOKEN upload_conda_package
 
  - <<: *conda_default
    stage: conda_package
    script:
      - doit --token=$CONDA_UPLOAD_TOKEN --label=main upload_conda_package
