name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install pyctdev to be able to install pyctdev :)"
        run: python -m pip install -e .
      - name: pip dev install
        run: python -m pyctdev develop_install --extra=ecosystem_pip --extra=tests
      - name: pip dev tests
        run: |
          pyctdev develop_test --test-group=all
          cd examples/one
          pyctdev develop_test --test-group=all
          cd ../two
          pyctdev develop_test --test-group=all
